# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)
# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
email:
recipients:
- solomatoff.vyacheslav@yandex.ru
on_success: never # default: change
on_failure: always # default: always
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE db_solomatov ENCODING = 'WIN1251';" -U postgres
  - psql -c "CREATE USER solomatov WITH PASSWORD '123';" -U postgres  
  - psql -c 'CREATE SCHEMA "solomatov" AUTHORIZATION solomatov;' -U postgres -d db_solomatov 
  - dotnet restore
